#!/bin/sh
set -e
cd $(dirname $0)

qemubin=qemu-system-x86_64
mac=mac=52:54:00:12:34:56

case "$1" in
-i386)
	qemubin=qemu-system-i386
	mac=mac=52:54:00:12:34:57
	shift
	;;
esac

case "$#" in
0)
	;;
*)
	echo 'usage: boot/qemu [-i386]' >&2
	exit 1
esac

echo '# building u9fs' >&2
make -C ../sys/src/cmd/unix/u9fs

u9fs="guestfwd=tcp:10.0.2.1:564-cmd:../sys/src/cmd/unix/u9fs/u9fs -a none -u $USER .."
tftp='tftp=..'
bootfile='bootfile=/386/9bootpxe'

kvmflag=
test -w /dev/kvm && kvmflag=-enable-kvm

$qemubin $kvmflag -m 2G -cpu host -smp 4 -serial stdio \
	-display sdl -boot n \
	-device VGA,vgamem_mb=64 \
	-device virtio-net-pci,netdev=net0,$mac \
	-netdev "user,id=net0,$u9fs,$tftp,$bootfile" \
	-usb -device usb-tablet
